### ISSUE TITLE
Parachelidura liui added without corresponding genus

### ISSUE THREAD

**Issue by permico** [sfg-taxonpages/dermaptera#10]
Hi Heidi

You have recently added Parachelidura liui Chen 2024 on DSF:
https://dermaptera.speciesfile.org/otus/1059823/overview

But there is no corresponding genus Parachelidura Chen 2024 present, the species is listed under subfamily directly.

Will be grateful if you can fix this issue by adding genus Parachelidura.

Kind regards, 

Boris

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added information about ongoing taxonomic updates and recent changes to the project description in the metadata.yml file.

You can review changes in this commit: https://github.com/lattaai13/sfg-taxonpages-dermaptera-10/commit/74dac7d4972f1a83cbb9a9939ee34fbc7c9be115.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by hhopkins77** [comment]
Thanks Boris. This has been fixed.
